### ISSUE TITLE
Better to unified the log form

### ISSUE THREAD

**Issue by fisherxu** [fisherxu/kubeedge#1]
Now in kubeedge we have two logs to used, 

the `log` #[github.com/kubeedge/beehive/pkg/common/log](github.com/kubeedge/beehive/pkg/common/log) 
E.g `log.LOGGER.Infof("ServiceBus receive msg")`

and `glog`# [github.com/golang/glog](github.com/golang/glog)
E.g `glog.V(8).Infof(format, data)`

In edged we used them both, but k8s only used the `glog`. 
And if upgrade edged version to k8s-v1.15, we need modify the `glog` in kubelet to `log`.

`Glog` also used in bluetooth_mapper/edged/integration test/e2e test/performance test and can set log level. 

We'd better to used a unified one, so do we use glog or log, any thoughts?

**Comment by kevin-wangzefeng** [comment]
# [RFC] Unifying logging library to glog
The `beehive logger` ["github.com/kubeedge/beehive/pkg/common/log"](https://github.com/kubeedge/beehive/tree/master/pkg/common/log)
E.g. ```log.LOGGER.Infof("ServiceBus receive msg")```

and `glog` ["github.com/golang/glog"](https://github.com/golang/glog)
E.g. ```glog.V(8).Infof(format, data)```

Today both of these logging libraries are used in edge_core, which is expensive to maintain and confusing to end users.
As we are going to upgrade edged base to k8s-v1.15, we'd better get this fixed first.
And choosing `glog` seems an easier way to stay align with upstream kubernetes.

The pros are:
    1.  logging liberary widely used by upstream kubernetes and subprojects
    2. support numeric log level
    3. already used in bluetooth_mapper, edged, integration test, e2e test and performance test

Any comments?
